### ISSUE TITLE
valve-bsp-parser.lib

### ISSUE THREAD

**Issue by gorilla1546** [ALittlePatate/CSS-external#8]
![изображение](https://github.com/ALittlePatate/CSS-external/assets/171955882/40ffa874-88ad-426f-9d59-0141ab3cf3b6)

**Comment by ALittlePatate** [comment]
make sure you have cloned the repo using --recursive :
`git clone https://github.com/ALittlePatate/CSS-external --recursive`

then open in visual studio and compile in x64 Release mode.
