### ISSUE TITLE
Cant use the aimbt

### ISSUE THREAD

**Issue by ofek222** [ALittlePatate/CSS-external#9]
So the cheat load perfectly fine but i cant use the aimbot
i dont have HOME bottom and i try to edit the code on visual studio but i get errors about the valve bsp thing 

are you able might release a copy of the game that the aimbot just set to mouse 2 or mouse 1 or maybe even manual edit XD
only if you can of course

**Comment by ALittlePatate** [comment]
well the aimbot is already bound on mouse 1, it is also bound to HOME but that's just for testing, you probably have to enable it in the menu (INSERT)

**Comment by ofek222** [comment]
> well the aimbot is already bound on mouse 1, it is also bound to HOME but that's just for testing, you probably have to enable it in the menu (INSERT)

god bless your kind soul
